include: package:flutter_lints/flutter.yaml

linter:
  rules:
    depend_on_referenced_packages: false
    library_private_types_in_public_api: false
dart_code_metrics:
  rules:
    - prefer-define-hero-tag
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - avoid-expanded-as-spacer
    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - consistent-update-render-object
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file
    - prefer-using-list-view
    - use-setstate-synchronously
    - avoid-incomplete-copy-with
    - proper-super-calls
    - dispose-fields
    - avoid-empty-setstate
    - prefer-widget-private-members
    - prefer-action-button-tooltip
    - avoid-inherited-widget-in-initstate
    - avoid-late-context
    - avoid-state-constructors
    - avoid-unnecessary-stateful-widgets
    - avoid-stateless-widget-initialized-fields
    - avoid-missing-image-alt
    - avoid-unnecessary-overrides-in-state
    - prefer-dedicated-media-query-methods
    - avoid-recursive-widget-calls
    - prefer-text-rich
    - prefer-sliver-prefix
    - avoid-single-child-column-or-row
    - avoid-undisposed-instances
    - avoid-unnecessary-gesture-detector
    - avoid-missing-controller
    - prefer-for-loop-in-children